export const ARGENTINE_TEAMS_LOCAL = [
  { team: { id: 26, name: "ESTA LOCURAAAA", logo: "https://media.api-sports.io/football/teams/26.png" } },
  { team: { id: 39, name: "NENAZO PREMIER LEAGUE", logo: "https://media.api-sports.io/football/leagues/39.png" } },
  { team: { id: 434, name: "Gimnasia L.P.", logo: "https://media.api-sports.io/football/teams/434.png" } },
  { team: { id: 435, name: "River Plate", logo: "https://media.api-sports.io/football/teams/435.png" } },
  { team: { id: 436, name: "Racing Club", logo: "https://media.api-sports.io/football/teams/436.png" } },
  { team: { id: 437, name: "Rosario Central", logo: "https://media.api-sports.io/football/teams/437.png" } },
  { team: { id: 438, name: "Velez Sarsfield", logo: "https://media.api-sports.io/football/teams/438.png" } },
  { team: { id: 439, name: "Godoy Cruz", logo: "https://media.api-sports.io/football/teams/439.png" } },
  { team: { id: 440, name: "Belgrano Cordoba", logo: "https://media.api-sports.io/football/teams/440.png" } },
  { team: { id: 441, name: "Union Santa Fe", logo: "https://media.api-sports.io/football/teams/441.png" } },
  { team: { id: 442, name: "Defensa Y Justicia", logo: "https://media.api-sports.io/football/teams/442.png" } },
  { team: { id: 445, name: "Huracan", logo: "https://media.api-sports.io/football/teams/445.png" } },
  { team: { id: 446, name: "Lanus", logo: "https://media.api-sports.io/football/teams/446.png" } },
  { team: { id: 449, name: "Banfield", logo: "https://media.api-sports.io/football/teams/449.png" } },
  { team: { id: 450, name: "Estudiantes L.P.", logo: "https://media.api-sports.io/football/teams/450.png" } },
  { team: { id: 451, name: "Boca Juniors", logo: "https://media.api-sports.io/football/teams/451.png" } },
  { team: { id: 452, name: "Tigre", logo: "https://media.api-sports.io/football/teams/452.png" } },
  { team: { id: 453, name: "Independiente", logo: "https://media.api-sports.io/football/teams/453.png" } },
  { team: { id: 455, name: "Atletico Tucuman", logo: "https://media.api-sports.io/football/teams/455.png" } },
  { team: { id: 456, name: "Talleres Cordoba", logo: "https://media.api-sports.io/football/teams/456.png" } },
  { team: { id: 457, name: "Newells Old Boys", logo: "https://media.api-sports.io/football/teams/457.png" } },
  { team: { id: 458, name: "Argentinos JRS", logo: "https://media.api-sports.io/football/teams/458.png" } },
  { team: { id: 460, name: "San Lorenzo", logo: "https://media.api-sports.io/football/teams/460.png" } },
  { team: { id: 473, name: "Independ. Rivadavia", logo: "https://media.api-sports.io/football/teams/473.png" } },
  { team: { id: 474, name: "Sarmiento Junin", logo: "https://media.api-sports.io/football/teams/474.png" } },
  { team: { id: 476, name: "Deportivo Riestra", logo: "https://media.api-sports.io/football/teams/476.png" } },
  { team: { id: 478, name: "Instituto Cordoba", logo: "https://media.api-sports.io/football/teams/478.png" } },
  { team: { id: 1064, name: "Platense", logo: "https://media.api-sports.io/football/teams/1064.png" } },
  { team: { id: 1065, name: "Central Cordoba de Santiago", logo: "https://media.api-sports.io/football/teams/1065.png" } },
  { team: { id: 2432, name: "Barracas Central", logo: "https://media.api-sports.io/football/teams/2432.png" } }
];